# Generated by Django 5.1.4 on 2025-01-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('carnet_identidad', models.CharField(max_length=11, unique=True)),
                ('chapa_vehiculo', models.CharField(max_length=20)),
                ('modelo_vehiculo', models.CharField(max_length=50)),
            ],
        ),
    ]
